### ISSUE TITLE
mitigating expensive resources

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/intro-to-algos-reading-group#2]
@indexzero - you mentioned that you have pdfs of the texts... do you think you could add them to this repo in a folder called resources?

**Comment by indexzero** [comment]
Sure thing once I get back in front of a computer!

**Comment by erunion** [comment]
There's a torrent of the book here http://kickass.to/introduction-to-algorithms-3rd-edition-t5780058.html, but I don't know if it would be a good idea to store that in the repo here for everyone.

**Comment by indexzero** [comment]
Done and done. https://github.com/ashleygwilliams/intro-to-algos-reading-group/pull/3

... come at me DMCA takedown notices. Knowledge should be free.
